[package]
name = "two-round-mpc"
version = "0.1.0"
edition = "2021"

[dependencies]
rand_core = { version = "0.6", features = ["std", "getrandom"] }

malachite = "0.4"

crypto-bigint = { version = "0.5", features = ["extra-sizes"] }
crypto-primes = "0.5"
